[versions]
android-compile-sdk = "33"
android-min-sdk = "24"
android-target-sdk = "33"
android-gradle-plugin = "7.3.1"
activity-compose = "1.6.1"
androidx-test = "1.5.0"
androidx-test-ext = "1.2.1"
androidx-test-runner = "1.5.1"
com-google-accompanist = "0.28.0"
compose = "1.3.1"
compose-compiler = "1.3.2"
coroutines = "1.6.4"
detekt = "1.21.0"
io-coil = "2.2.2"
java = "11"
junit = "4.13.2"
kermit = "1.2.2"
koin = "3.2.2"
koin-android = "3.3.0"
kotlin = "1.7.20"
ktor = "2.1.2"
nav-compose = "2.5.0"
turbine = "0.12.1"
versions-ben-manes = "0.44.0"
viewModel-ktx = "2.5.1"
kotlinx-serialization= "1.4.0"
native-coroutines = "0.13.1"
androidx-compose-material3 = "1.0.0-rc01"

[libraries]
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-lifecycle-viewModel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "viewModel-ktx" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "nav-compose" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
cashapp-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
com-google-accompanist-system-ui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "com-google-accompanist" }
io-coil = { module = "io.coil-kt:coil", version.ref = "io-coil" }
io-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "io-coil" }
io-gitlab-arturbosch-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-kotlinx-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }

[bundles]
androidx-test = ["androidx-test-core", "androidx-test-ext-junit", "androidx-test-rules", "androidx-test-runner"]
compose = ["androidx-activity-activity-compose", "androidx-compose-foundation", "androidx-compose-material-icons-core", "androidx-compose-material-icons-extended", "androidx-compose-runtime", "androidx-compose-ui", "androidx-compose-ui-ui-test", "androidx-compose-ui-ui-tooling", "androidx-navigation-navigation-compose", "androidx-compose-compiler", "androidx-compose-material3", "io-coil-compose"]
koin = ["koin-android", "koin-compose", "koin-core"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
touchlab-kermit = { id = "co.touchlab.kermit", version.ref = "kermit" }
versionsBenManes = { id = "com.github.ben-manes.versions", version.ref = "versions-ben-manes" }
native-coroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "native-coroutines" }
